### ISSUE TITLE
Use JS from CDN?

### ISSUE THREAD

**Issue by tomkyle** [animaux/largeformat#1]
My suggestion is to load jQuery and Datatables from a CDN, since both builds are widely-used and often load faster:

- cdnjs.com for jQuery and
- datatables CDN for the custom build

**Comment by animaux** [comment]
Sorry, no, DS-GVO.

**Comment by tomkyle** [comment]
*read…read…read* well, that's a valid point. Thx for hinting me at this.

**Comment by animaux** [comment]
`;)` I wasn’t a friend of third party hosted software before … but now.
